In [1]:
import pandas as pd
import numpy as np
import requests
import json
import geopandas as gpd
import datetime
pd.set_option('display.max_rows', 500)

In [2]:
apikey = 'S0hVKhVwDwLu25K2QrxgLwN4aScka'

In [3]:
def get_json(point1, point2, apikey, dt = datetime.datetime.now()):
    dt = str(int(time.mktime(dt.timetuple())))
    query = 'https://api.distancematrix.ai/maps/api/distancematrix/json?origins=' + point1 + '&destinations=' + point2 + '&key=' + apikey + '&departure_time=' + dt
    results = requests.get(query)
    return results.text

La siguiente funcion toma como input una base de datos como el BEAM y calcula las distancias entre las ciudades de un mismo pais

In [4]:
def calculate_distances_from_df(database):
    final_df = []
    for country in database['COUNTRY'].unique():
        df = database[database['COUNTRY'] == country]
        for x in df['MAIN_CITY'].unique():
            pointa = df[df['MAIN_CITY'] == x]
            country = pointa['COUNTRY'].values[0]
            citya = pointa['MAIN_CITY'].values[0]
            latlonga = pointa['point'].values[0]
            for y in df['MAIN_CITY'].unique():
                if x != y:
                    pointb = df[df['MAIN_CITY'] == y]
                    cityb = pointb['MAIN_CITY'].values[0]
                    latlongb = pointb['point'].values[0]
                    print(citya,cityb,sep = ' to ')
                    response = get_json(latlonga,latlongb,apikey)
                    data = json.loads(response)

                    distance = data['rows'][0]['elements'][0]['distance']['text']
                    duration = data['rows'][0]['elements'][0]['duration']['text']
                    duration_in_traffic = data['rows'][0]['elements'][0]['duration_in_traffic']['text']
                    datapoint = [country,citya,latlonga,cityb,latlongb,distance,duration,duration_in_traffic]
                    final_df.append(datapoint)
                else:
                    continue

    data_final = pd.DataFrame(final_df)
    data_final.columns = ['Country','City A','Point A','City B','Point B','Distance','Duration','Duration in traffic']
    return data_final

In [5]:
distances = pd.read_excel('shipment/distances.xlsx', index_col = 0)

In [6]:
cwpops = pd.read_excel('shipment/cwpops.xlsx', index_col = [0,1])

Obtengo latitudes y longitudes de las ciudades

In [7]:
latlongs = distances[['Country','City A','Point A']].rename(
    columns = {'Point A':'latlong','City A':'City'}
).drop_duplicates('City').set_index(['Country','City']).dropna()
latlongs[['lat','long']] = latlongs['latlong'].apply(lambda x: pd.Series(x.split(','))).astype(float)
latlongs = latlongs.drop('latlong', axis = 1)

Joineo con latlongs y creo GeoDataFrame

In [8]:
cwpops = cwpops.join(latlongs)

cwpops = gpd.GeoDataFrame(
    cwpops, geometry=gpd.points_from_xy(cwpops.long, cwpops.lat))

#### Funciones

In [9]:
def get_wages_from_cutoff(city_index, cutoff):
    city_wage = cwpops.drop_duplicates('index1').loc[city_index]['estimated_citywage']
    distan = distances[(distances['Country'] == city_index[0])
                            &(distances['City A'] == city_index[1])
                            &(distances['parsed_duration'] <= cutoff)].drop_duplicates('City B')

    nearby_cities = [(x,y) for x,y in distan[['Country','City B']].values.tolist()]
    if len(nearby_cities) == 0:
        return city_wage
    else:
        nearby_wages = cwpops.loc[nearby_cities]['estimated_citywage'].sum()
        return nearby_wages + city_wage

In [10]:
def get_countryshare_from_cutoff(city_index, cutoff, share_out = True):
    nearwages = get_wages_from_cutoff(city_index, cutoff = cutoff)
    country_wages = cwpops.groupby('Country')['estimated_citywage'].sum().loc[city_index[0]]
    share = nearwages/country_wages
    if share_out == True:
        return share
    else:
        return nearwages

In [11]:
samplecities = [('Mexico','Mexicali'),
                ('Mexico','La Laguna'), 
                ('Mexico','Villahermosa'),
                ('Mexico','Hermosillo'),
               ('Promedios','Promedio de Mexico'),
               ('Promedios','Promedio de Latam')]

In [12]:
shares_cutoff = pd.DataFrame(index = cwpops.index)

shares_cutoff['index1'] = shares_cutoff.index
for i in range(10):
    shares_cutoff['cutoff_' + str(i)] = shares_cutoff['index1'].apply(
                lambda x: get_countryshare_from_cutoff(x, cutoff = i))

shares_cutoff = pd.concat([shares_cutoff, shares_cutoff.mean().to_frame(('Promedios','Promedios')).T])

In [13]:
shares_cutoff.head()

                                                                             index1  \
Country   City
Argentina Bahia Blanca-Cerri                        (Argentina, Bahia Blanca-Cerri)
          Ciudad de Buenos Aires                (Argentina, Ciudad de Buenos Aires)
          Comodoro Rivadavia-Rada Tilly  (Argentina, Comodoro Rivadavia-Rada Tilly)
          Concordia                                          (Argentina, Concordia)
          Corrientes                                        (Argentina, Corrientes)

                                         cutoff_0  cutoff_1  cutoff_2  \
Country   City
Argentina Bahia Blanca-Cerri             0.011226  0.011226  0.011226
          Ciudad de Buenos Aires         0.154551  0.649061  0.656603
          Comodoro Rivadavia-Rada Tilly  0.011787  0.011787  0.011787
          Concordia                      0.004644  0.004644  0.004644
          Corrientes                     0.008136  0.015559  0.015559

                                         cutoff_3  cutoff_4  cutoff_5  \
Country   City
Argentina Bahia Blanca-Cerri             0.011226  0.017859  0.021465
          Ciudad de Buenos Aires         0.661993  0.703915  0.735604
          Comodoro Rivadavia-Rada Tilly  0.011787  0.011787  0.011787
          Concordia                      0.004644  0.025364  0.716347
          Corrientes                     0.021267  0.028124  0.028124

                                         cutoff_6  cutoff_7  cutoff_8  \
Country   City
Argentina Bahia Blanca-Cerri             0.044904  0.058093  0.721373
          Ciudad de Buenos Aires         0.756324  0.759999  0.822065
          Comodoro Rivadavia-Rada Tilly  0.012797  0.012797  0.012797
          Concordia                      0.737415  0.751695  0.795858
          Corrientes                     0.032768  0.032768  0.072944

                                         cutoff_9
Country   City
Argentina Bahia Blanca-Cerri             0.732676
          Ciudad de Buenos Aires         0.826967
          Comodoro Rivadavia-Rada Tilly  0.017570
          Concordia                      0.805172
          Corrientes                     0.072944

In [14]:
meanlat = shares_cutoff.mean().to_frame()
meanlat.columns = pd.MultiIndex.from_tuples([('Promedios','Promedio de Latam')])

shares_cutoff = pd.concat([shares_cutoff,meanlat.T])

In [15]:
meanmex = shares_cutoff.loc['Mexico'].mean().to_frame()
meanmex.columns = pd.MultiIndex.from_tuples([('Promedios','Promedio de Mexico')])

shares_cutoff = pd.concat([shares_cutoff,meanmex.T])

In [29]:
shares_cutoff.loc[samplecities].head(10)

                                              index1  cutoff_0  cutoff_1  \
Country   City
Mexico    Mexicali                (Mexico, Mexicali)  0.010809  0.010809
          La Laguna              (Mexico, La Laguna)  0.015397  0.021012
          Villahermosa        (Mexico, Villahermosa)  0.004418  0.004418
          Hermosillo            (Mexico, Hermosillo)  0.013132  0.013132
Promedios Promedio de Mexico                     NaN  0.013158  0.018502
          Promedio de Latam                      NaN  0.028436  0.049014

                              cutoff_2  cutoff_3  cutoff_4  cutoff_5  \
Country   City
Mexico    Mexicali            0.012794  0.032980  0.036447  0.036447
          La Laguna           0.021012  0.031094  0.272939  0.290804
          Villahermosa        0.004418  0.013591  0.019680  0.020955
          Hermosillo          0.016047  0.020102  0.022638  0.022638
Promedios Promedio de Mexico  0.045280  0.069442  0.116032  0.147745
          Promedio de Latam   0.093179  0.129435  0.184963  0.228399

                              cutoff_6  cutoff_7  cutoff_8  cutoff_9
Country   City
Mexico    Mexicali            0.038983  0.038983  0.052115  0.052115
          La Laguna           0.326639  0.342401  0.385002  0.418377
          Villahermosa        0.033889  0.039193  0.054975  0.082797
          Hermosillo          0.025407  0.025407  0.071710  0.082519
Promedios Promedio de Mexico  0.196858  0.232394  0.265545  0.308419
          Promedio de Latam   0.276425  0.320506  0.356644  0.392882

In [17]:
shares_cutoff_abs = pd.DataFrame(index = cwpops.index)

shares_cutoff_abs['index1'] = shares_cutoff_abs.index
for i in range(10):
    shares_cutoff_abs['cutoff_' + str(i)] = shares_cutoff_abs['index1'].apply(
        lambda x: get_countryshare_from_cutoff(x, cutoff = i, share_out = False))

In [18]:
meanlat = shares_cutoff_abs.mean().to_frame()
meanlat.columns = pd.MultiIndex.from_tuples([('Promedios','Promedio de Latam')])

shares_cutoff_abs = pd.concat([shares_cutoff_abs,meanlat.T])

In [19]:
meanmex = shares_cutoff_abs.loc['Mexico'].mean().to_frame()
meanmex.columns = pd.MultiIndex.from_tuples([('Promedios','Promedio de Mexico')])

shares_cutoff_abs = pd.concat([shares_cutoff_abs,meanmex.T])

In [28]:
shares_cutoff_abs.loc[samplecities].head(10)

                                              index1      cutoff_0  \
Country   City
Mexico    Mexicali                (Mexico, Mexicali)  3.507796e+06
          La Laguna              (Mexico, La Laguna)  4.996485e+06
          Villahermosa        (Mexico, Villahermosa)  1.433792e+06
          Hermosillo            (Mexico, Hermosillo)  4.261625e+06
Promedios Promedio de Mexico                     NaN  4.269997e+06
          Promedio de Latam                      NaN  3.311592e+06

                                  cutoff_1      cutoff_2      cutoff_3  \
Country   City
Mexico    Mexicali            3.507796e+06  4.151839e+06  1.070253e+07
          La Laguna           6.818746e+06  6.818746e+06  1.009055e+07
          Villahermosa        1.433792e+06  1.433792e+06  4.410667e+06
          Hermosillo          4.261625e+06  5.207712e+06  6.523564e+06
Promedios Promedio de Mexico  6.004182e+06  1.469413e+07  2.253537e+07
          Promedio de Latam   4.596678e+06  8.966107e+06  1.283636e+07

                                  cutoff_4      cutoff_5      cutoff_6  \
Country   City
Mexico    Mexicali            1.182784e+07  1.182784e+07  1.265083e+07
          La Laguna           8.857401e+07  9.437175e+07  1.060010e+08
          Villahermosa        6.386509e+06  6.800151e+06  1.099758e+07
          Hermosillo          7.346549e+06  7.346549e+06  8.245012e+06
Promedios Promedio de Mexico  3.765461e+07  4.794624e+07  6.388444e+07
          Promedio de Latam   1.908236e+07  2.473592e+07  3.155213e+07

                                  cutoff_7      cutoff_8      cutoff_9
Country   City
Mexico    Mexicali            1.265083e+07  1.691245e+07  1.691245e+07
          La Laguna           1.111158e+08  1.249406e+08  1.357717e+08
          Villahermosa        1.271903e+07  1.784055e+07  2.686942e+07
          Hermosillo          8.245012e+06  2.327118e+07  2.677898e+07
Promedios Promedio de Mexico  7.541655e+07  8.617473e+07  1.000881e+08
          Promedio de Latam   3.824880e+07  4.507881e+07  5.205920e+07